### ISSUE TITLE
Ruby 2.6.0 deprecation warning about error class

### ISSUE THREAD

**Issue by mjankowski** [maccman/nestful#36]
Error looks like:

> [...]/nestful-1.1.3/lib/nestful/connection.rb:76: warning: constant Net::HTTPServerException is deprecated

If you have a preference re: solution here...

- Remove it outright with understanding that older ruby versions might throw that error?
- Make that list of errors conditional on which ruby version is being used?
- Something else?

...I'd be happy to assist with PR.

**Comment by predatorian3** [comment]
Maybe this will help? 

https://bugs.ruby-lang.org/issues/14688
